---
- name: Remove kube-proxy manifest
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml
    state: absent

- name: Loop over defined cilium values
  ansible.builtin.template:
    src: "cni/{{ item }}.j2"
    dest: "/var/lib/rancher/rke2/server/manifests/{{ item }}"
    mode: '0644'
  loop:
    - rke2-cilium-base.yaml
  notify: Restart RKE2 server

- name: Download Gateway API CRD files
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/{{ item.path }}/{{ item.name }}"
    dest: "{{ manifest_dir }}{{ item.name }}"
    mode: '0644'
    force: true
  loop: "{{ gateway_api_crds }}"
  notify: Restart RKE2 server
