---
- name: 'Create /etc/rancher/{{ rancherk8s_type }}'
  ansible.builtin.file:
    state: directory
    path: '/etc/rancher/{{ rancherk8s_type }}'
    mode: '0755'

- name: 'Set config-file for {{ rancherk8s_type }}'
  ansible.builtin.template:
    src: config.yml.j2
    dest: '/etc/rancher/{{ rancherk8s_type }}/config.yaml'
    mode: '0644'
  notify: Restart server
