---
- name: Append kubectl binary dir to global PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/k8s_exports.sh
    line: "{{ item }}"
    mode: '0644'
    create: true
  loop:
    - 'export PATH="$PATH:/var/lib/rancher/{{ rancherk8s_type }}/bin"'
    - 'export KUBECONFIG={{ rancherk8s_kubeconfig }}'

- name: "Create rancherk8s_kubeconfig dir"
  ansible.builtin.file:
    path: "{{ rancherk8s_kubeconfig | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: 'Start installation server node for {{ rancherk8s_type }}'
  ansible.builtin.include_tasks: install/server.yml
  when:
    - "'server_primary' in group_names"

- name: 'Start installation agent node for {{ rancherk8s_type }}'
  ansible.builtin.include_tasks: install/agent.yml
  loop: "{{ groups.agent }}"
  when:
    - "'agent' in group_names"
    - hostvars[item].inventory_hostname == inventory_hostname

- name: Store node-token
  ansible.builtin.set_fact:
    rancherk8s_token: "{{ hostvars[groups['server_primary'][0]]['node_token'].content | b64decode | regex_replace('\n', '') }}"

- name: Create cluster with all server-nodes
  ansible.builtin.include_tasks: install/cluster.yml
  # Join secondary servers one at a time (independent of the playbook's to avoid an etcd quorum race during bootstrap.
  throttle: 1
  when:
    - "'server_secondary' in group_names"

- name: Set RKE2 login-file permissions
  when: rancherk8s_type == 'rke2'
  ansible.builtin.copy:
    src: "/etc/rancher/rke2/rke2.yaml"
    dest: "{{ rancherk8s_kubeconfig }}"
    mode: '0644'
    remote_src: true

- name: Disable automated updates of RKE2
  when: rancherk8s_type == 'rke2'
  ansible.builtin.replace:
    path: /etc/yum.repos.d/rancher-rke2.repo
    regexp: '^enabled=1'
    replace: 'enabled=0'
