---
- name: Pre-flight
  ansible.builtin.include_tasks: pre_flight.yml

- name: Install prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: 'Configure config-file for {{ rancherk8s_type }}'
  ansible.builtin.include_tasks: configure.yml
  when:
    - "'server_primary' in group_names"

- name: "Install version: {{ rancherk8s_version }}"
  ansible.builtin.include_tasks: install.yml
  when:
    - rancherk8s_bin.stat.exists is false

- name: Configure CNI, ServiceAccount and tooling
  when: "'server_primary' in group_names"
  block:
    - name: Configure CNI
      ansible.builtin.include_tasks: cni.yml

    - name: "Setup service account sa-{{ rancherk8s_service_account }}"
      ansible.builtin.include_tasks: service-account.yml

    - name: Restart k8s
      ansible.builtin.meta: flush_handlers

    - name: Install tooling for maintaining the clusters
      ansible.builtin.include_tasks: tools.yml
      when:
        - rancherk8s_install_tools

- name: Install Cilium
  when:
    - "'server_primary' in group_names"
    - rancherk8s_type == 'k3s'
    - rancherk8s_cni == 'cilium'
  ansible.builtin.include_tasks: tools/cilium.yml

- name: Install fluxcd for managing cluster
  ansible.builtin.include_tasks: tools/fluxcd.yml
  when:
    - "'server_primary' in group_names"

- name: Setup initial labels
  ansible.builtin.include_tasks: labels.yml
  when: labels is defined

- name: "Upgrade environment to {{ rancherk8s_version_defined }}"
  ansible.builtin.include_tasks: upgrade.yml
  when:
    - rancherk8s_version_defined is version(rancherk8s_version_installed, '>')
    - rancherk8s_allow_upgrade is true

- name: "Show API token"  # noqa no-handler
  when:
    - "'server_primary' in group_names"
    - rancherk8s_sa.changed
  ansible.builtin.debug:
    msg:
      - "This token below is only shown during creation of the rke2-cluster."
      - "The token is base64 encoded and can be used as API-token:"
      - "{{ rancherk8s_sa_token.resources.0.data.token }}"
