---
- name: "Create ClusterRoleBinding"
  kubernetes.core.k8s:
    namespace: kube-system
    state: present
    template: 'service-account/clusterrolebinding.yml.j2'
    kubeconfig: '{{ rke2_kubeconfig }}'

- name: Create sa-account
  block:
    - name: "Create sa-{{ rke2_service_account }} and token"  # noqa name[template]
      kubernetes.core.k8s:
        namespace: kube-system
        state: present
        template: 'service-account/user.yml.j2'
        kubeconfig: '{{ rke2_kubeconfig }}'
      register: rke2_sa

- name: "Gather token for sa-{{ rke2_service_account }}"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: kube-system
    name: "sa-{{ rke2_service_account }}-token"
    kubeconfig: '{{ rke2_kubeconfig }}'
  register: rke2_sa_token
