---
- name: Start installation RKE2 server node
  ansible.builtin.include_tasks: install/server.yml
  loop: "{{ groups.rke2_server }}"
  when:
    - "'rke2_server' in group_names"
    - hostvars[item].inventory_hostname == inventory_hostname

- name: Start installation RKE2 agent node
  ansible.builtin.include_tasks: install/agent.yml
  loop: "{{ groups.rke2_agent }}"
  when:
    - "'rke2_agent' in group_names"
    - hostvars[item].inventory_hostname == inventory_hostname
