---
- name: Check for existing token
  ansible.builtin.stat:
    path: /var/lib/rancher/rke2/server/node-token
  register: node_token_stat

- name: Read and register node-token from first server
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token
  when:
    - node_token_stat.stat.exists

- name: Store node-token
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  when:
    - node_token_stat.stat.exists
