- name: Check if Cilium CLI is already installed
  ansible.builtin.command: cilium version --client
  register: current_cilium_version
  failed_when: false
  changed_when: false

- name: Get latest Cilium CLI version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: true
  register: rancherk8s_cilium_cli_version

- name: Determine if installation/upgrade is needed
  ansible.builtin.set_fact:
    needs_install_cli: "{{ not cilium_cli_installed or (current_cli_version != cilium_cli_version) }}"
  vars:
    cilium_cli_version: "{{ rancherk8s_cilium_cli_version.content | trim }}"
    cilium_cli_installed: "{{ current_cilium_version.rc == 0 }}"
    current_cli_version: "{{ (current_cilium_version.stdout | regex_findall('cilium-cli: (v?[0-9.]+)') | first) | default('') }}"

- name: "Install Cilium CLI {{ rancherk8s_cilium_cli_version.content | trim }}"
  when: needs_install_cli
  block:
    - name: Download Cilium CLI binary
      ansible.builtin.get_url:
        url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz"
        dest: "/usr/local/bin/"
        mode: '0644'
      vars:
        cilium_cli_version: "{{ rancherk8s_cilium_cli_version.content | trim }}"

    - name: Extract Cilium CLI to /usr/local/bin
      ansible.builtin.unarchive:
        src: "/usr/local/bin/cilium-linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        owner: root
        group: root
        mode: '0755'

    - name: Remove cilium installation file
      ansible.builtin.file:
        path: "/usr/local/bin/cilium-linux-amd64.tar.gz"
        state: absent
