- name: Check if Cilium CLI is already installed
  ansible.builtin.command: cilium version --client
  register: current_cilium_version
  failed_when: false
  changed_when: false

- name: Get latest Cilium CLI version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: true
  register: rancherk8s_cilium_version

- name: Determine if installation/upgrade is needed
  ansible.builtin.set_fact:
    needs_install: "{{ not cilium_installed or (current_version != cilium_cli_version) }}"
  vars:
    cilium_cli_version: "{{ rancherk8s_cilium_version.content | trim }}"
    cilium_installed: "{{ current_cilium_version.rc == 0 }}"
    current_version: "{{ (current_cilium_version.stdout | regex_findall('cilium-cli: (v?[0-9.]+)') | first) | default('') }}"

- name: "Install Cilium {{ rancherk8s_cilium_version.content | trim }}"
  when: needs_install
  block:
    - name: Download Cilium CLI binary
      ansible.builtin.get_url:
        url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz"
        dest: "/usr/local/bin/"
        mode: '0644'
      vars:
        cilium_cli_version: "{{ rancherk8s_cilium_version.content | trim }}"

    - name: Extract Cilium CLI to /usr/local/bin
      ansible.builtin.unarchive:
        src: "/usr/local/bin/cilium-linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        owner: root
        group: root
        mode: '0755'

    - name: Remove cilium installation file
      ansible.builtin.file:
        path: "/usr/local/bin/cilium-linux-amd64.tar.gz"
        state: absent

- name: Add cilium chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io"

- name: Install cilium using Helm
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ rancherk8s_cni_cilium_version }}"
    release_namespace: kube-system
    kubeconfig: '{{ rancherk8s_kubeconfig }}'
    reuse_values: true
    values:
      k8sServiceHost: "127.0.0.1"
      k8sServicePort: 6443
      ipam:
        operator:
          clusterPoolIPv4PodCIDRList:
            - "10.42.0.0/16"
      operator:
        replicas: "{{ rancherk8s_cni_operator_replicas }}"
    state: present
