- name: Install k9s
  ansible.builtin.dnf:
    name: "{{ 'https://github.com/derailed/k9s/releases/download/' ~ rancherk8s_k9s_version ~ '/k9s_linux_amd64.rpm'
      if rancherk8s_k9s_version | length > 0
      else 'https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.rpm' }}"
    state: present
    disable_gpg_check: true

- name: User xterm-256color for k9s
  ansible.builtin.copy:
    dest: /etc/profile.d/k9s.sh
    content: |
      alias k9s='TERM=xterm-256color k9s'
    mode: '0644'
    owner: root
    group: root
